package com.example.utils

object AppStrings {
    val isEn: Boolean
        get() = FormatUtils.currentLanguage == "EN"

    val currentCurrency: String
        get() = FormatUtils.currentCurrency

    // Navigation Tabs
    val tabHome get() = if (isEn) "Home" else "Trang chủ"
    val tabTransactions get() = if (isEn) "Transactions" else "Giao dịch"
    val tabAnalytics get() = if (isEn) "Analytics & Budget" else "Báo cáo & Ngân sách"
    val tabWallets get() = if (isEn) "Wallets & Tools" else "Ví & Tiện ích"
    val tabSettings get() = if (isEn) "Settings" else "Cài đặt"

    // Home Screen
    val selectWallet get() = if (isEn) "Select Wallet" else "Chọn Ví Tiền"
    val totalWalletBalance get() = if (isEn) "Total Wallet Balance" else "Tổng Số Dư Các Ví"
    val allWallets get() = if (isEn) "All Wallets" else "Tất cả ví"
    val income get() = if (isEn) "Income" else "Thu nhập"
    val expense get() = if (isEn) "Expense" else "Chi tiêu"
    val netBalance get() = if (isEn) "Net Surplus" else "Thặng dư net"
    val recentTransactions get() = if (isEn) "Recent Transactions" else "Giao dịch gần đây"
    val viewAll get() = if (isEn) "View All" else "Xem tất cả"
    val noTransactions get() = if (isEn) "No transactions found" else "Chưa có giao dịch nào"
    val categoryBreakdown get() = if (isEn) "Category Breakdown" else "Chi tiêu theo danh mục"
    val budgetStatus get() = if (isEn) "Budget Status" else "Trạng thái ngân sách"
    val savingsGoals get() = if (isEn) "Savings Goals" else "Mục tiêu tiết kiệm"
    val upcomingBills get() = if (isEn) "Upcoming Bills" else "Hóa đơn sắp tới"
    val overBudget get() = if (isEn) "Over budget" else "Vượt ngân sách"
    val safeBudget get() = if (isEn) "Within budget" else "Trong mức an toàn"

    // Time Periods
    val periodToday get() = if (isEn) "Today" else "Hôm nay"
    val periodWeek get() = if (isEn) "This Week" else "Tuần này"
    val periodMonth get() = if (isEn) "This Month" else "Tháng này"
    val periodYear get() = if (isEn) "This Year" else "Năm nay"
    val periodAll get() = if (isEn) "All Time" else "Tất cả"

    // Transactions Screen
    val searchPlaceholder get() = if (isEn) "Search transactions..." else "Tìm kiếm giao dịch..."
    val filterAll get() = if (isEn) "All" else "Tất cả"
    val filterExpense get() = if (isEn) "Expense" else "Chi tiêu"
    val filterIncome get() = if (isEn) "Income" else "Thu nhập"
    val totalCount get() = if (isEn) "Total Transactions" else "Tổng số giao dịch"

    // Add / Edit Transaction
    val newTransactionTitle get() = if (isEn) "Add New Transaction" else "Thêm Giao Dịch Mới"
    val editTransactionTitle get() = if (isEn) "Edit Transaction" else "Sửa Giao Dịch"
    val expenseToggle get() = if (isEn) "Expense (-)" else "Chi tiêu (-)"
    val incomeToggle get() = if (isEn) "Income (+)" else "Thu nhập (+)"
    val amountLabel get() = if (isEn) "Amount ($currentCurrency) *" else "Số tiền ($currentCurrency) *"
    val selectWalletLabel get() = if (isEn) "Select Wallet" else "Chọn Ví Tiền Thực Hiện"
    val walletLabel get() = if (isEn) "Wallet" else "Ví Tiền"
    val categoryLabel get() = if (isEn) "Category" else "Danh mục"
    val titleLabel get() = if (isEn) "Title / Detail Name" else "Tiêu đề / Tên chi tiết"
    val titlePlaceholder get() = if (isEn) "e.g. Lunch, Monthly Salary..." else "Ví dụ: Ăn trưa bún chả, Tiền lương..."
    val transactionDate get() = if (isEn) "Transaction Date" else "Ngày giao dịch"
    val noteLabel get() = if (isEn) "Note (Optional)" else "Ghi chú (Không bắt buộc)"
    val saveTransaction get() = if (isEn) "Save Transaction" else "Lưu Giao Dịch"
    val updateTransaction get() = if (isEn) "Update Transaction" else "Cập Nhật Giao Dịch"
    val invalidAmount get() = if (isEn) "Please enter a valid amount" else "Vui lòng nhập số tiền hợp lệ"
    val close get() = if (isEn) "Close" else "Đóng"
    val select get() = if (isEn) "Select" else "Chọn"
    val cancel get() = if (isEn) "Cancel" else "Hủy"

    // Budget Dialog
    val budgetTitle get() = if (isEn) "Set Budget Limit" else "Thiết lập ngân sách"
    val budgetLimitLabel get() = if (isEn) "Monthly Spending Limit ($currentCurrency)" else "Hạn mức chi tiêu tháng ($currentCurrency)"
    val budgetSave get() = if (isEn) "Save Limit" else "Lưu Hạn Mức"

    // Wallets & Tools Tabs
    val tabWalletsList get() = if (isEn) "My Wallets" else "Ví Của Tôi"
    val tabDebts get() = if (isEn) "Debts & Loans" else "Sổ Nợ & Vay"
    val tabSavings get() = if (isEn) "Savings Goals" else "Hũ Tiết Kiệm"
    val tabBills get() = if (isEn) "Recurring Bills" else "Hóa Đơn Định Kỳ"

    // Wallets & Tools Details
    val walletsManagement get() = if (isEn) "Wallets Management" else "Quản lý ví tiền"
    val addWallet get() = if (isEn) "Add New Wallet" else "Thêm ví mới"
    val walletName get() = if (isEn) "Wallet Name" else "Tên ví"
    val initialBalance get() = if (isEn) "Initial Balance" else "Số dư ban đầu"
    val walletType get() = if (isEn) "Wallet Category" else "Loại ví tiền"
    val typeCash get() = if (isEn) "Cash" else "Tiền mặt"
    val typeBank get() = if (isEn) "Bank Account" else "Ngân hàng"
    val typeEWallet get() = if (isEn) "E-Wallet" else "Ví điện tử"
    val typeCredit get() = if (isEn) "Credit Card" else "Thẻ tín dụng"
    val transferMoney get() = if (isEn) "Transfer Money" else "Chuyển Tiền"
    val debtsManagement get() = if (isEn) "Debts & Loans" else "Sổ nợ & Cho vay"
    val recurringBillsManagement get() = if (isEn) "Recurring Bills" else "Hóa đơn định kỳ"
    val recurringBills get() = if (isEn) "Recurring Bills" else "Hóa đơn định kỳ"
    val payBillBtn get() = if (isEn) "Pay" else "Thanh toán"
    val settleDebtBtn get() = if (isEn) "Settle" else "Tất toán"
    val settledLabel get() = if (isEn) "Settled" else "Đã xong"
    val paid get() = if (isEn) "Paid" else "Đã thanh toán"
    val unpaid get() = if (isEn) "Unpaid" else "Chưa thanh toán"

    // Deletion Confirmations
    val deleteConfirmTitle get() = if (isEn) "Confirm Deletion" else "Xác Nhận Xóa"
    val deleteWalletMsg get() = if (isEn) "Are you sure you want to delete this wallet?" else "Bạn có chắc chắn muốn xóa ví tiền này không?"
    val deleteDebtMsg get() = if (isEn) "Are you sure you want to delete this debt entry?" else "Bạn có chắc chắn muốn xóa khoản nợ này không?"
    val deleteGoalMsg get() = if (isEn) "Are you sure you want to delete this savings goal?" else "Bạn có chắc chắn muốn xóa mục tiêu tiết kiệm này không?"
    val deleteBillMsg get() = if (isEn) "Are you sure you want to delete this recurring bill?" else "Bạn có chắc chắn muốn xóa hóa đơn định kỳ này không?"
    val deleteBtn get() = if (isEn) "Delete" else "Xóa"

    // Category Strings
    val addCategoryTitle get() = if (isEn) "Add New Category" else "Thêm Danh Mục Mới"
    val categoryNameLabel get() = if (isEn) "Category Name" else "Tên danh mục"
    val categoryTypeLabel get() = if (isEn) "Category Type" else "Loại danh mục"
    val categoryIconLabel get() = if (isEn) "Choose Icon" else "Chọn Biểu Tượng"
    val categoryColorLabel get() = if (isEn) "Choose Color" else "Chọn Màu Sắc"
    val addNewCategoryBtn get() = if (isEn) "+ Add New" else "+ Thêm Mới"
    val allCategoriesLabel get() = if (isEn) "All Categories" else "Tất cả danh mục"

    // Settings Screen
    val securityTitle get() = if (isEn) "Fingerprint & Device Lock" else "Xác Thực Vân Tay & Khóa Thiết Bị"
    val securityEnabled get() = if (isEn) "Biometric login protection ON" else "Đang bật bảo mật đăng nhập"
    val securityDisabled get() = if (isEn) "Protection disabled" else "Chưa bật bảo mật"
    val lockNow get() = if (isEn) "Lock Screen Now" else "Khóa Màn Hình Ngay"
    val changePin get() = if (isEn) "Change Backup PIN" else "Đổi Mã PIN Backup"
    val themeTitle get() = if (isEn) "Appearance Theme" else "Chế Độ Giao Diện"
    val themeSystem get() = if (isEn) "System Default" else "Theo Hệ Thống"
    val themeLight get() = if (isEn) "Light Mode" else "Giao Diện Sáng"
    val themeDark get() = if (isEn) "Dark Mode" else "Giao Diện Tối"
    val languageTitle get() = if (isEn) "App Language" else "Ngôn Ngữ Ứng Dụng"
    val currencyTitle get() = if (isEn) "Currency Unit" else "Đơn Vị Tiền Tệ"
    val dataTitle get() = if (isEn) "Data Management" else "Quản Lý Dữ Liệu"
    val insertSample get() = if (isEn) "Insert Sample Data" else "Thêm Dữ Liệu Mẫu"
    val clearAll get() = if (isEn) "Clear All Data" else "Xóa Toàn Bộ Dữ Liệu"
    val exportCsv get() = if (isEn) "Export CSV Data" else "Xuất Dữ Liệu CSV"
    val copyCsv get() = if (isEn) "Copy CSV Data" else "Sao Chép Dữ Liệu CSV"
    val expandDataOptions get() = if (isEn) "Tap to view options" else "Bấm để mở các tùy chọn"
    val collapseDataOptions get() = if (isEn) "Tap to hide options" else "Bấm để thu gọn"

    // Privacy Banner & App Info
    val privacyBannerTitle get() = if (isEn) "Local Storage Only (Offline)" else "Lưu Trữ Cục Bộ (Local Only)"
    val privacyBannerDesc get() = if (isEn) "All your financial data is encrypted and stored locally in the SQLite (Room) database on your phone, never sent to any backend server." else "Toàn bộ dữ liệu tài chính của bạn được mã hóa và lưu trực tiếp trong cơ sở dữ liệu SQLite (Room) trên điện thoại, hoàn toàn không đẩy lên máy chủ backend."
    val aboutAppTitle get() = if (isEn) "App Information" else "Thông Tin Ứng Dụng"
    val appNameDesc get() = if (isEn) "Money Zen Personal Finance App" else "Ứng dụng quản lý tài chính cá nhân Money Zen"
    val appVersion get() = if (isEn) "Version 1.0.0" else "Phiên bản: 1.0.0"
    val clearDataTitle get() = if (isEn) "Clear All Data?" else "Xóa Toàn Bộ Dữ Liệu?"
    val clearDataMsg get() = if (isEn) "This action will permanently delete all transactions and budgets on your device. This cannot be undone." else "Hành động này sẽ xóa tất cả giao dịch và ngân sách trên thiết bị của bạn. Không thể hoàn tác."
    val clearDataConfirm get() = if (isEn) "Delete All Now" else "Xóa Ngay"
    val changePinTitle get() = if (isEn) "Change Backup PIN (4 digits)" else "Đổi Mã PIN Backup (4 chữ số)"
    val changePinDesc get() = if (isEn) "PIN used for backup login when biometric authentication is unavailable." else "Mã PIN dùng để đăng nhập dự phòng khi sinh trắc học không sẵn sàng."
    val newPinLabel get() = if (isEn) "Enter new 4-digit PIN" else "Nhập PIN 4 số mới"
    val savePin get() = if (isEn) "Save PIN" else "Lưu PIN"

    // Biometric Lock Screen
    val appProtectionTitle get() = if (isEn) "FINANCIAL SECURITY" else "BẢO MẬT TÀI CHÍNH"
    val appProtectionMsg get() = if (isEn) "Application is protected. Please authenticate via fingerprint, face, or device lock to proceed." else "Ứng dụng được bảo vệ. Vui lòng xác thực vân tay, khuôn mặt hoặc khóa thiết bị để tiếp tục."
    val triggerBiometricBtn get() = if (isEn) "Fingerprint / Unlock Device" else "Xác Thực Vân Tay / Mở Khóa"
    val enterBackupPinBtn get() = if (isEn) "Enter Backup PIN" else "Nhập Mã PIN Backup"
    val pinDialogTitle get() = if (isEn) "Enter Security PIN" else "Nhập Mã PIN Bảo Mật"
    val defaultPinNote get() = if (isEn) "Default: 1234 (Can be changed in Settings)" else "Mặc định: 1234 (Có thể thay đổi trong Cài Đặt)"
    val incorrectPin get() = if (isEn) "Incorrect PIN, try again!" else "Mã PIN không đúng, thử lại!"

    // Dialog & Spending Limit Strings
    val addBillTitle get() = if (isEn) "Add Recurring Bill" else "Thêm Hóa Đơn Định Kỳ"
    val billTitleLabel get() = if (isEn) "Bill Title (e.g. Electricity)" else "Tên hóa đơn (VD: Điện T8)"
    val frequencyLabel get() = if (isEn) "Payment Frequency" else "Tần suất thanh toán"
    val deductWalletLabel get() = if (isEn) "Deduct from Wallet" else "Trích từ ví"
    val saveBill get() = if (isEn) "Save Bill" else "Lưu Hóa Đơn"
    val transferTitle get() = if (isEn) "Transfer Between Wallets" else "Chuyển Tiền Giữa Các Ví"
    val fromWalletLabel get() = if (isEn) "From Wallet (Debit)" else "Ví gửi (Trừ tiền)"
    val toWalletLabel get() = if (isEn) "To Wallet (Credit)" else "Ví nhận (Cộng tiền)"
    val transferAmountLabel get() = if (isEn) "Transfer Amount" else "Số tiền chuyển"
    val confirmTransfer get() = if (isEn) "Confirm Transfer" else "Xác Nhận Chuyển"
    val addDebtTitle get() = if (isEn) "Add New Debt / Loan" else "Thêm Ghi Nợ Mới"
    val personNameLabel get() = if (isEn) "Person Name" else "Tên người vay / cho vay"
    val lendBtn get() = if (isEn) "Lend (+)" else "Cho Vay"
    val borrowBtn get() = if (isEn) "Borrow (-)" else "Đi Vay"
    val noteReasonLabel get() = if (isEn) "Note / Reason" else "Ghi chú lý do"
    val saveDebt get() = if (isEn) "Save Debt" else "Lưu Sổ Nợ"
    val addGoalTitle get() = if (isEn) "Create Savings Goal" else "Tạo Mục Tiêu Tiết Kiệm Mới"
    val goalTitleLabel get() = if (isEn) "Goal Title (e.g. Vacation, Laptop)" else "Tên mục tiêu (Ví dụ: Mua iPhone, Du lịch)"
    val targetAmountLabel get() = if (isEn) "Target Amount" else "Số tiền mục tiêu cần đạt"
    val createGoal get() = if (isEn) "Create Goal" else "Tạo Mục Tiêu"
    val walletMonthlyLimit get() = if (isEn) "Monthly Limit" else "Hạn mức tháng"
    val walletMonthlyLimitSetting get() = if (isEn) "Monthly Limit (0 = No limit)" else "Hạn mức chi tiêu tháng (0 = Không hạn mức)"
    val limitWarningWallet get() = if (isEn) "Exceeded wallet monthly limit!" else "Cảnh báo: Đã vượt hạn mức chi tiêu của ví!"
    val limitWarningOverall get() = if (isEn) "Exceeded overall monthly spending limit!" else "Cảnh báo: Đã vượt quá tổng hạn mức chi tiêu hàng tháng!"
    val setOverallLimit get() = if (isEn) "Set Total Spending Limit" else "Đặt Hạn Mức Tổng Chi Tiêu"
    val overallLimitTitle get() = if (isEn) "Overall Monthly Spending Limit" else "Tổng Hạn Mức Chi Tiêu Hàng Tháng"
    val noLimitSet get() = if (isEn) "No limit set" else "Chưa đặt hạn mức"
    val overallSpendingWarning get() = if (isEn) "OVERALL MONTHLY SPENDING ALERT" else "CẢNH BÁO TỔNG CHI TIÊU THÁNG"
    val walletSpendingWarning get() = if (isEn) "WALLET SPENDING ALERT" else "CẢNH BÁO CHI TIÊU VÍ"

    // Home & Analytics
    val spendingReportTitle get() = if (isEn) "Spending Report" else "Báo Cáo Chi Tiêu"
    val viewDetails get() = if (isEn) "View Details" else "Xem chi tiết"
    val topSpendingCategories get() = if (isEn) "Top Spending Categories:" else "Danh mục chi tiêu nhiều nhất:"
    val budgetWarningTitle get() = if (isEn) "Budget Alert!" else "Cảnh báo ngân sách chi tiêu!"
    fun budgetWarningMsg(count: Int) = if (isEn) "$count categories exceeded or near monthly limit." else "Có $count danh mục đã vượt/gần chạm hạn mức ngân sách tháng."
    val mySavingsGoals get() = if (isEn) "My Savings Goals" else "Hũ Tiết Kiệm Của Tôi"
    val latestTransactions get() = if (isEn) "Latest Transactions" else "Giao Dịch Mới Nhất"
    val noTransactionsPeriod get() = if (isEn) "No transactions found in this period." else "Chưa có giao dịch nào trong khoảng thời gian này."
    val detailedReportTitle get() = if (isEn) "Detailed Report" else "Báo Cáo Chi Tiết"
    val incomeVsExpenseRatio get() = if (isEn) "Income vs Expense Ratio" else "Tỷ Lệ Thu vs Chi"
}
